HomeBudgetRazor/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeBudgetRazor.Pages
{
    [AllowAnonymous]
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Description later";
        }
    }
}

HomeBudgetRazor/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeBudgetRazor.Pages
{
    [AllowAnonymous]
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Fill later";
        }
    }
}

HomeBudgetRazor/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeBudgetRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

HomeBudgetRazor/Pages/ImportExport.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using HomeBudgetRazor.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace HomeBudgetRazor.Pages
{
    public class ImportExportModel : PageModel
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly Models.HomeBudgetRazorContext _context;
        public ImportExportModel(IHostingEnvironment hostingEnvironment, Models.HomeBudgetRazorContext context)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostExport()
        {
            var currentUser = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var expenses = from e in _context.Expense
                           where e.OwnerID == currentUser
                           select e;

            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string sFileName = @"demo.xlsx";
            string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, sFileName);
            FileInfo file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            var memory = new MemoryStream();
            using (var fs = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Create, FileAccess.Write))
            {
                IWorkbook workbook;
                workbook = new XSSFWorkbook();
                ISheet excelSheet = workbook.CreateSheet("Demo");

                IRow row = excelSheet.CreateRow(0);

                row.CreateCell(0).SetCellValue("Date of expense");
                row.CreateCell(1).SetCellValue("Amount");
                row.CreateCell(2).SetCellValue("Category");
                row.CreateCell(3).SetCellValue("Description");

                var i = 1;
                foreach(var expense in expenses)
                {
                    row = excelSheet.CreateRow(i);
                    row.CreateCell(0).SetCellValue(expense.DateOfExpense.ToString("dd/MM/yyyy"));
                    
                    row.CreateCell(1).SetCellValue(expense.Amount.ToString());
                    row.CreateCell(2).SetCellValue(expense.Category);
                    row.CreateCell(3).SetCellValue(expense.Description);
                    i++;
                }

                workbook.Write(fs);
            }

            using (var stream = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }

        public async Task<IActionResult> OnPostImport()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName);
                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook   
                    }

                    

                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        var expense = new Expense();
                        IRow row = sheet.GetRow(i);
                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

                        if (row.GetCell(row.FirstCellNum) != null)
                            expense.DateOfExpense = Convert.ToDateTime(row.GetCell(row.FirstCellNum).ToString());
                        if (row.GetCell(row.FirstCellNum+1) != null)
                            expense.Amount = Convert.ToDecimal(row.GetCell(row.FirstCellNum+1).ToString());
                        if (row.GetCell(row.FirstCellNum + 2) != null)
                            expense.Category = row.GetCell(row.FirstCellNum + 2).ToString();
                        if (row.GetCell(row.FirstCellNum + 3) != null)
                            expense.Description= row.GetCell(row.FirstCellNum + 3).ToString();

                        //expense.Id = _context.Expense.Select(x => x.Id).Max() + 1;

                        var currentUser = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                        expense.OwnerID = currentUser;
                        _context.Expense.Add(expense);
                    }


                    await _context.SaveChangesAsync();                 
                }
            }
            return RedirectToPage("./Index");
        }
    }
}

HomeBudgetRazor/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using HomeBudgetRazor.Data;
using HomeBudgetRazor.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace HomeBudgetRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly HomeBudgetRazorContext _context;

        public IndexModel(HomeBudgetRazorContext context)
        {
            _context = context;
        }

        public IList<Expense> Expense { get; set; }
        public string StringForChart { get; set; }


        public async Task OnGetAsync()
        {
            var currentUser = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Expense = await _context.Expense.Where(x => x.OwnerID == currentUser).ToListAsync();

            StringForChart = CreateStringForChart(currentUser);
        }

        private string CreateStringForChart(string currentUser)
        {
            Dictionary<string, decimal> amountByCategory = _context.Expense.Where(x=>x.OwnerID == currentUser).GroupBy(m => m.Category).ToDictionary(g => g.Key, g => g.Sum(x => x.Amount));

            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("[['Category', 'Amount'],");
            foreach (var item in amountByCategory)
            {
                sb.AppendFormat("['{0}', {1}],", item.Key, item.Value.ToString().Replace(",", "."));
            }
            sb.AppendFormat("]");
            return sb.ToString();
        }
        //public async Task OnGetAsync()
        //{           
        //    AllExpenses = await _db.AllExpenses.AsNoTracking().ToListAsync();
        //}

        //public async Task<IActionResult> OnPostDeleteAsync(int id)
        //{
        //    var expense = await _db.AllExpenses.FindAsync(id);

        //    if (expense != null)
        //    {
        //        _db.AllExpenses.Remove(expense);
        //        await _db.SaveChangesAsync();
        //    }

        //    return RedirectToPage();
        //}
    }
}

HomeBudgetRazor/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HomeBudgetRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HomeBudgetRazor/Pages/About.cshtml
@page 
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>

HomeBudgetRazor/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    Mati<br />
    Ełk, WM 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    XXXXXXXX
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">xxxx@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">xxxxx@example.com</a>
</address>

HomeBudgetRazor/Pages/ImportExport.cshtml
@page
@model HomeBudgetRazor.Pages.ImportExportModel
@{
    ViewData["Title"] = "ImportExport";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Import or export excel files</h2>

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-4">
            <input type="file" id="fUpload" name="files" class="form-control" />
        </div>
        <div class="col-md-8">
            <input type="button" id="btnUpload" value="Upload" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-8" style="padding-top:10px;">
            <button asp-page-handler="Export">Export</button>
        </div>
    </div>
    <br />
    <div id="dvData"></div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript" language="JavaScript">
        $(document).ready(function () {
            $('#btnUpload').on('click', function () {
                var fileExtension = ['xls', 'xlsx'];
                var filename = $('#fUpload').val();
                if (filename.length == 0) {
                    alert("Please select a file.");
                    return false;
                }
                else {
                    var extension = filename.replace(/^.*\./, '');
                    if ($.inArray(extension, fileExtension) == -1) {
                        alert("Please select only excel files.");
                        return false;
                    }
                }
                var fdata = new FormData();
                var fileUpload = $("#fUpload").get(0);
                var files = fileUpload.files;
                fdata.append(files[0].name, files[0]);
                $.ajax({
                    type: "POST",
                    url: "/ImportExport?handler=Import",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    data: fdata,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.length == 0)
                            alert('Some error occured while uploading');
                        else {
                            $('#dvData').html(response);
                        }
                    },
                    error: function (e) {
                        $('#dvData').html(e.responseText);
                    }
                });
            })
        });
    </script>
}

HomeBudgetRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h3>Summary:</h3>
<div class="row">
    <div class="col-xs-6">
        <div id="chart1"></div>
    </div>
    <div class="col-xs-6">
        <div id="chart2"></div>
    </div>
</div>
<div id="chart1"></div>
<h3>Your last expenses:</h3>
<p>
    <a asp-page="./Expenses/Create">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Expense[0].DateOfExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Expense[0].Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Expense[0].Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Expense[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Expense)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfExpense)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-page="./Expenses/Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Expenses/Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Expenses/Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable(@Html.Raw(Model.StringForChart), false);

            // Simple Pie Chart:
            var option = {
                title: 'Expenses by category: ',
                width: 500,
                height: 300
            };

            var formatter = new google.visualization.NumberFormat({ decimalSymbol: ',' });
            formatter.format(data, 1);

            var chart = new google.visualization.PieChart(document.getElementById('chart1'));
            var chart2 = new google.visualization.PieChart(document.getElementById('chart2'));
            chart.draw(data, option);
            chart2.draw(data, option);
        }
    </script>
}